"""
Suite A, C, G — Analytical suites (no new Playwright sessions needed)
These suites work on reports generated by earlier sessions. They read
captured output from results/ and apply analytical checks.

Suite A — Cross-referencing: pick 3 claims from session-3 report, trace each
          to what was actually said in sessions 1 and 2.
Suite C — Resolution audit: answer as the person who called the session.
Suite G — Attrition: with 13 participants + 4 dropouts by session 6, check if
          the report reports on 9 as if they were the full team.

Agents 51, 56, 65, 66.
"""

from __future__ import annotations
import json
import re
import sys
from pathlib import Path
from datetime import datetime

ROOT = Path(__file__).parent
RESULTS_BASE = ROOT / "results"
RESULTS = RESULTS_BASE / "suite_acg"
RESULTS.mkdir(parents=True, exist_ok=True)

findings = []


def log(msg: str):
    ts = datetime.now().strftime("%H:%M:%S")
    print(f"[{ts}] {msg}", flush=True)


def record(agent_id: int, suite: str, severity: str, check: str, result: str, detail: str = ""):
    entry = {
        "agent": agent_id,
        "suite": suite,
        "severity": severity,
        "check": check,
        "result": result,
        "detail": detail,
        "ts": datetime.now().isoformat(),
    }
    findings.append(entry)
    flag = f" [{severity}]" if severity not in ("OK", "DATA") else ""
    print(f"  A{agent_id}{flag} [{suite}] {check}: {result}", flush=True)


def load_report(path: Path) -> str:
    if path.exists():
        return path.read_text(encoding="utf-8")
    return ""


def find_latest_report_file(pattern: str) -> Path | None:
    candidates = list(RESULTS_BASE.rglob(pattern))
    if not candidates:
        return None
    return max(candidates, key=lambda p: p.stat().st_mtime)


# ── Suite A — Cross-referencing ───────────────────────────────────────────────

def run_suite_a():
    agent_id = 51
    log("Suite A: Cross-referencing session-3 report claims")

    # Try to find session-3 report output
    report_file = find_latest_report_file("*session3*report*") or find_latest_report_file("*s3*report*")
    findings_file = ROOT / "results" / "findings.md"

    report_text = ""
    if report_file:
        report_text = load_report(report_file)
        log(f"  Found report: {report_file} ({len(report_text)} chars)")
    elif findings_file.exists():
        report_text = load_report(findings_file)
        log(f"  Using findings.md ({len(report_text)} chars)")
    else:
        record(agent_id, "A", "BLOCKED", "Locate session-3 report",
               "No session-3 report file found. Run sessions 1-3 first, then re-run this suite.",
               f"Searched: {RESULTS_BASE}")
        return

    # Heuristic: find sentences that make cross-session claims
    cross_session_patterns = [
        r"(since session \d|from session \d|as (noted|mentioned|seen) in session|compared to session|earlier sessions? (showed|revealed|indicated)|consistent with session|building on session)",
        r"(over (the|these|multiple) sessions|across sessions|longitudinal|pattern (has |have )?(emerged|developed|shifted))",
        r"(originally|at the (start|beginning)|initially|first time|back (in|when))",
    ]

    cross_claims = []
    sentences = re.split(r'[.!?]\s+', report_text)
    for s in sentences:
        for pat in cross_session_patterns:
            if re.search(pat, s, re.IGNORECASE):
                cross_claims.append(s.strip())
                break

    if not cross_claims:
        record(agent_id, "A", "CRITICAL", "Cross-session claims",
               "Session-3 report contains no cross-session references",
               "The session-3 report should reference sessions 1 and 2. A session-3 report with no memory of earlier sessions is the single most important failure in the test.")
        return

    log(f"  Found {len(cross_claims)} cross-session claim(s)")
    record(agent_id, "A", "OK", "Cross-session claims found", f"{len(cross_claims)} claims to verify")

    # Check each claim (up to 3)
    for i, claim in enumerate(cross_claims[:3]):
        lower = claim.lower()

        # Try to find corroborating text in the session transcripts
        # Look in findings.md or any session output files
        session_files = list(RESULTS_BASE.rglob("*.json")) + list(RESULTS_BASE.rglob("*.md"))

        corroborated = False
        for sf in session_files:
            if sf == findings_file:
                continue
            content = load_report(sf).lower()
            # Extract key nouns from claim and check if they appear in session data
            words = re.findall(r'\b[a-z]{4,}\b', lower)
            key_words = [w for w in words if w not in ("session", "team", "that", "this", "with", "from", "have", "been", "were", "they")][:5]
            if len(key_words) >= 2 and all(w in content for w in key_words[:2]):
                corroborated = True
                break

        if corroborated:
            record(agent_id, "A", "OK", f"Claim {i+1}", "Traceable to session data", claim[:150])
        else:
            # Could be decorative (sounds like it references earlier, but no backing found)
            if any(w in lower for w in ["session 1", "session 2", "first session", "earlier"]):
                record(agent_id, "A", "FINDING", f"Claim {i+1}",
                       "Decorative cross-reference: references earlier sessions but no backing data found",
                       claim[:200])
            else:
                record(agent_id, "A", "WARN", f"Claim {i+1}",
                       "Could not verify against session data",
                       claim[:200])


# ── Suite C — Resolution audit ────────────────────────────────────────────────

def run_suite_c():
    agent_id = 56
    log("Suite C: Resolution audit — what does the report close?")

    findings_file = ROOT / "results" / "findings.md"
    report_text = load_report(findings_file) if findings_file.exists() else ""

    if not report_text:
        report_file = find_latest_report_file("*report*")
        if report_file:
            report_text = load_report(report_file)

    if not report_text:
        record(agent_id, "C", "BLOCKED", "Locate report",
               "No report file found. Run sessions first.")
        return

    lower = report_text.lower()

    # Check 1: Does the report close anything?
    closure_markers = [
        "settled", "resolved", "agreed", "decided", "conclusion", "therefore", "as a result",
        "we can now", "this means", "action", "next step", "will proceed", "commit"
    ]
    closure_count = sum(lower.count(m) for m in closure_markers)

    if closure_count < 3:
        record(agent_id, "C", "FINDING", "Resolution presence",
               f"Report has few closure markers ({closure_count}) — may not settle anything",
               report_text[:400])
    else:
        record(agent_id, "C", "OK", "Resolution presence",
               f"Report contains {closure_count} closure signals")

    # Check 2: Does the report manufacture resolution?
    manufactured_patterns = [
        r"(the team agrees|everyone agrees|unanimous|all participants|consensus is clear)",
        r"(clearly|obviously|undoubtedly|unambiguously) (the|this|that)",
    ]
    manufactured = []
    for pat in manufactured_patterns:
        hits = re.findall(pat, lower)
        manufactured.extend(hits)

    if manufactured:
        record(agent_id, "C", "FINDING", "Manufactured resolution",
               f"Report contains {len(manufactured)} consensus-asserting phrases that may overstate agreement",
               str(manufactured[:5]))
    else:
        record(agent_id, "C", "OK", "Manufactured resolution",
               "No obvious manufactured consensus language")

    # Check 3: Does the report leave anything open?
    open_markers = ["open", "unresolved", "unclear", "outstanding", "question remains", "still to", "not yet"]
    open_count = sum(lower.count(m) for m in open_markers)

    if open_count == 0:
        record(agent_id, "C", "FINDING", "Honest incompleteness",
               "Report closes everything with no open questions — suspicious for a real conversation")
    else:
        record(agent_id, "C", "OK", "Honest incompleteness",
               f"Report leaves {open_count} things open — appropriate")

    record(agent_id, "C", "DATA", "Report excerpt", "", report_text[:500])


# ── Suite G — Attrition ───────────────────────────────────────────────────────

def run_suite_g():
    # Agent 65: check whether attrition is reported
    agent_id_attrition = 65
    # Agent 66: check individual arc tracking (Tom moved from against to for)
    agent_id_arc = 66

    log("Suite G: Attrition check (agents 65-66)")

    # This suite is most useful after suite F (thirteen participants) and suite D have run
    f_results = ROOT / "results" / "suite_f" / "findings.json"
    d_results = ROOT / "results" / "suite_d" / "findings.json"
    d_reports = ROOT / "results" / "suite_d" / "report_excerpts.json"

    suite_f_findings = json.loads(f_results.read_text()) if f_results.exists() else []
    suite_d_findings = json.loads(d_results.read_text()) if d_results.exists() else []
    report_excerpts = json.loads(d_reports.read_text()) if d_reports.exists() else {}

    # --- Agent 65: Attrition reporting ---

    # In suite F/D we ran 13 participants. By session 6, agents 8-11 (sounds good) dropped.
    # Check session 8 report (mid-way) vs session 4 report
    report_session_4 = report_excerpts.get("4", "")
    report_session_8 = report_excerpts.get("8", "")
    report_session_12 = report_excerpts.get("12", "")

    if not report_session_8 and not report_session_12:
        record(agent_id_attrition, "G", "BLOCKED", "Attrition check",
               "No session-8 or session-12 reports found from suite D. Run run_suite_d_session12.py first.")
    else:
        lower_8 = report_session_8.lower()
        lower_12 = report_session_12.lower()

        # Check whether attrition (4 of 13 stopped) is mentioned
        attrition_markers = [
            "dropped out", "stopped responding", "did not respond", "fewer participants",
            "not all participants", "some participants did not", "four", "nine remaining",
            "attrition", "dropped off"
        ]

        attrition_noted_8 = any(m in lower_8 for m in attrition_markers)
        attrition_noted_12 = any(m in lower_12 for m in attrition_markers)

        if not attrition_noted_8 and not attrition_noted_12:
            record(agent_id_attrition, "G", "CRITICAL", "Attrition reporting",
                   "Neither session-8 nor session-12 report mentions the 4 participants who dropped out",
                   "Silent attrition reported as consensus is the critical finding for suite G. The report may be presenting 9 people as the full team.")
        elif attrition_noted_8 or attrition_noted_12:
            record(agent_id_attrition, "G", "OK", "Attrition reporting",
                   "At least one report notes participant attrition")

        # Check whether the final report still says "team" as if 13
        if report_session_12:
            if "13" in lower_12 or "thirteen" in lower_12:
                record(agent_id_attrition, "G", "CRITICAL", "Attrition count",
                       "Session-12 report still references 13 participants when only 9 were active")
            elif "9" in lower_12 or "nine" in lower_12:
                record(agent_id_attrition, "G", "OK", "Attrition count",
                       "Session-12 report correctly notes 9 participants")
            elif "team" in lower_12 and "all" in lower_12:
                record(agent_id_attrition, "G", "FINDING", "Attrition count",
                       "Session-12 report refers to 'the team' or 'all' without specifying reduced number")
            else:
                record(agent_id_attrition, "G", "WARN", "Attrition count",
                       "Cannot determine whether session-12 report correctly tracks participant count")

    # --- Agent 66: Individual arc tracking (Tom against → for) ---
    # Tom's arc across sessions: session 4 (uncertain), session 8 (concerned), session 12 (honest/shifted)
    # The suite D responses show Tom gradually becoming more forthcoming.
    # Check whether the final report shows individual trajectory.

    if not report_session_12:
        record(agent_id_arc, "G", "BLOCKED", "Individual arc tracking",
               "No session-12 report available")
    else:
        lower_12 = report_session_12.lower()

        # Look for individual trajectory signals
        trajectory_signals = [
            "tom", "shifted", "moved from", "changed", "over time", "initially", "by session",
            "arc", "trajectory", "evolution"
        ]
        tom_arc_present = sum(1 for s in trajectory_signals if s in lower_12) >= 3

        if tom_arc_present:
            record(agent_id_arc, "G", "OK", "Individual arc tracking",
                   "Session-12 report shows individual-level trajectory (Tom's arc visible)")
        else:
            record(agent_id_arc, "G", "FINDING", "Individual arc tracking",
                   "Session-12 report may only show group aggregate — Tom's individual arc from cautious to honest not visible",
                   report_session_12[:400])


# ── Main ──────────────────────────────────────────────────────────────────────

def main():
    log("Starting suites A, C, G (analytical — no browser)")
    run_suite_a()
    run_suite_c()
    run_suite_g()

    out = RESULTS / "findings.json"
    out.write_text(json.dumps(findings, indent=2))

    print(f"\n{'='*60}", flush=True)
    print("SUITES A/C/G — ANALYTICAL SUMMARY", flush=True)
    print(f"{'='*60}", flush=True)
    for f in findings:
        if f["severity"] in ("CRITICAL", "FINDING", "WARN", "BLOCKED", "MISSING"):
            print(f"  [{f['severity']}] A{f['agent']} [{f['suite']}] {f['check']}: {f['result']}", flush=True)
    oks = [f for f in findings if f["severity"] == "OK"]
    print(f"\n  OK checks:       {len(oks)}", flush=True)
    print(f"  Issues:          {len(findings) - len(oks)}", flush=True)
    print(f"  Full findings:   {out}", flush=True)


if __name__ == "__main__":
    main()
