ALTER TYPE "GroundScenario" ADD VALUE IF NOT EXISTS 'OKR_ALIGNMENT';
ALTER TYPE "GroundScenario" ADD VALUE IF NOT EXISTS 'WORKPLAN_BUDGET';
ALTER TYPE "GroundScenario" ADD VALUE IF NOT EXISTS 'PULSE_CHECK';
ALTER TYPE "GroundScenario" ADD VALUE IF NOT EXISTS 'REALIGN_TEAM';
ALTER TYPE "GroundScenario" ADD VALUE IF NOT EXISTS 'PIP';
