import {
  softSpots,
  whatWouldRaiseIt,
  readIsSafeToShow,
  NOT_ENOUGH_HERE,
  type AccountShape,
  type SoftSpot,
} from './harder-to-fool';

/**
 * THE FAILURE MODE IS NOT A BAD REPORT. IT IS A CONFIDENT ONE. (G34, G35)
 *
 * Everything else built this week makes the picture better. These two ask what
 * happens when it is wrong - because a reader takes a board at the confidence the
 * board projects, and a board that raises confidence without raising accuracy
 * converts a hunch into a decision about somebody.
 *
 * G34 is the part that is easy to build badly. A cheat detector would be the
 * worst thing in this codebase: an accusation generated by a regex, about a
 * person, permanently, from signals that are innocent most of the time. So the
 * assertions here are as much about what these functions REFUSE to say as about
 * what they notice.
 */

const clean: AccountShape = {
  sessions: 4, corroborated: 3, specifics: 6, repeatedSpecifics: 1,
  documents: 2, documentsReferredTo: 2,
};

describe('where the record is easiest to be wrong about', () => {
  it('says nothing at all about a record with nothing to say about', () => {
    expect(softSpots(clean)).toEqual([]);
  });

  it('notices an account nothing else in the ground touches', () => {
    const [{ spot, line }] = softSpots({ ...clean, corroborated: 0 });
    expect(spot).toBe('nothing else touches it');
    // The distinction the whole module turns on.
    expect(line).toMatch(/does not make it wrong, it makes it unchecked/);
  });

  it('does not call one lonely session a soft spot', () => {
    // Session one is uncorroborated by definition. Flagging it would fire on
    // every new ground, and a signal that fires on everything is noise that
    // teaches people to ignore the real ones.
    expect(softSpots({ ...clean, sessions: 1, corroborated: 0 })).toEqual([]);
  });

  it('notices detail that never moves, and grants the innocent reading in the same sentence', () => {
    const [{ spot, line }] = softSpots({ ...clean, specifics: 5, repeatedSpecifics: 4 });
    expect(spot).toBe('the detail does not move');
    expect(line).toMatch(/that is what steady work looks like/);
  });

  it('notices documents nothing refers to', () => {
    // The easiest signal in the product to satisfy on purpose: attaching is one
    // click, and every measure of "document backed" counts it.
    const [{ spot, line }] = softSpots({ ...clean, documents: 3, documentsReferredTo: 0 });
    expect(spot).toBe('documents nobody uses');
    expect(line).toMatch(/treat this as an account without documents/);
  });

  it('never accuses anybody of anything', () => {
    // THE REGRESSION THIS FILE EXISTS FOR. Every one of these signals has an
    // innocent cause that is more likely than the guilty one, and the moment a
    // line here implies a motive it is an accusation the product cannot support
    // and the person cannot answer.
    const all = softSpots({ sessions: 6, corroborated: 0, specifics: 5, repeatedSpecifics: 5, documents: 2, documentsReferredTo: 0 });
    expect(all).toHaveLength(3);
    for (const { line } of all) {
      for (const pattern of [
        /gam(?:e|ing|ed)\b/i, /cheat/i, /fak(?:e|ing|ed)/i, /dishonest/i, /misleading/i,
        /suspicious/i, /appears? to be/i, /deliberate/i, /inflat/i, /\bthey\b/i,
      ]) {
        // The "they" ban caught "They are not doing any work in this picture",
        // where "they" was the documents. Rather than narrow the pattern, the
        // line names the documents - because in a paragraph about a person's
        // record, an unattached "they" is genuinely ambiguous to a reader too,
        // and the reader is the one this is for.
        expect({ line, pattern: String(pattern), hit: pattern.test(line) }).toMatchObject({ hit: false });
      }
    }
  });
});

describe('a soft spot never travels alone', () => {
  it.each<SoftSpot>(['nothing else touches it', 'the detail does not move', 'documents nobody uses'])(
    'every one of them says what would raise it: %s',
    (spot) => {
      // Without this, the honest half ("we are less sure here") lands as the
      // accusing half ("something is off about this person"). The remedy is what
      // turns it back into a fact about the record.
      const fix = whatWouldRaiseIt(spot);
      expect(fix).toMatch(/^Ask /);
      expect(fix.length).toBeGreaterThan(40);
    },
  );

  it('and the remedy for unmoving detail accepts the innocent answer', () => {
    // The one that would otherwise become a demand to perform change.
    expect(whatWouldRaiseIt('the detail does not move')).toMatch(/accept "nothing" as an answer/);
  });
});

describe('a board that will not guess', () => {
  const read = { line: 'Delivery is behind because the handover never happened.' };

  it('shows a read the record supports', () => {
    expect(readIsSafeToShow(read, { band: 'well covered' }, [])).toMatchObject({ show: true, instead: null });
  });

  it('refuses on a thin picture', () => {
    // G35 IN ONE ASSERTION. This is the case a normal product ships: the read is
    // plausible, the data is thin, and showing both lets the reader take the
    // first at the confidence of the second.
    const { show, instead } = readIsSafeToShow(read, { band: 'thin' }, []);
    expect(show).toBe(false);
    expect(instead).toMatch(/a guess wearing a report's clothes/);
  });

  it('refuses when nothing has been scored, rather than treating empty as fine', () => {
    expect(readIsSafeToShow(read, { band: 'nothing yet' }, []).show).toBe(false);
  });

  it('refuses on two soft spots even where the picture looks well covered', () => {
    // Coverage and trustworthiness are different things, and this is the case
    // where they point opposite ways: plenty of material, none of it checked
    // against anything.
    const spots = [{ spot: 'nothing else touches it' as SoftSpot }, { spot: 'documents nobody uses' as SoftSpot }];
    expect(readIsSafeToShow(read, { band: 'well covered' }, spots).show).toBe(false);
  });

  it('tolerates one', () => {
    expect(readIsSafeToShow(read, { band: 'well covered' }, [{ spot: 'the detail does not move' as SoftSpot }]).show).toBe(true);
  });

  it('and says blank is a finding, not a failure', () => {
    // The sentence that decides whether a lead reads the empty board as the
    // product being broken or as the ground being young.
    expect(NOT_ENOUGH_HERE).toMatch(/Blank is a finding/);
    expect(NOT_ENOUGH_HERE).toMatch(/where to look next/);
  });
});
