/**
 * HARDER TO FOOL, INCLUDING BY ITSELF. (G34, G35)
 *
 * Everything else in this repo makes the picture better. These two ask what
 * happens when it is wrong, because the failure mode of this product is not a bad
 * report - it is a confident one.
 *
 * G34, THE THING SOMEBODY CAN DO ON PURPOSE. A person who works out what the
 * product rewards can produce it without doing the work: name numbers, name
 * dates, attach a document, say the specific-sounding thing. Every signal here
 * measures the ACCOUNT, and an account is written by somebody who can see what
 * gets a good result. That is not paranoia about people; it is what happens to
 * every measure that gets used, and the ones that survive it are the ones that
 * are expensive to fake rather than easy to detect.
 *
 * So the checks below are not a cheat detector. A cheat detector would be the
 * worst thing in this codebase: an accusation generated by a regex, about
 * somebody, permanently. What they do instead is notice when the SIGNALS AND THE
 * SUBSTANCE COME APART, and say it as a fact about the record:
 *
 *   detail that never changes         a description written once and repeated
 *   numbers nobody else ever touches  specific, and load-bearing on one account
 *   documents nothing refers to       attached, never used, never mentioned again
 *
 * Each of those is also completely innocent most of the time. A stable project
 * has stable detail. So the output is never a verdict and never names a cause -
 * it lowers CONFIDENCE and says what would raise it, which is the only response
 * that is right whether the cause is dishonesty, a boring quarter, or somebody
 * who writes the same way every week.
 *
 * G35, THE LIABILITY. A board that raises a reader's confidence without raising
 * accuracy is worse than no board, because it converts a hunch into a decision.
 * Everything above is scaffolding for one rule: where the picture cannot support
 * a read, the product says so LOUDER than it says the read.
 */

export interface AccountShape {
  /** Distinct sessions this person completed. */
  sessions: number;
  /** How many of their statements anybody else's account also touches. */
  corroborated: number;
  /**
   * How many of their statements anybody else COULD have touched.
   *
   * Targets are excluded upstream, because only the person who set one can state it.
   * Without this number a lead who correctly spent the ground stating targets is
   * indistinguishable from somebody whose account nobody could reach - opposite
   * situations, same zero.
   */
  corroborable?: number;
  /** How many statements carry a checkable specific at all. */
  specifics: number;
  /** Of those, how many repeat a specific already given in an earlier session. */
  repeatedSpecifics: number;
  /** Documents attached. */
  documents: number;
  /** Of those, how many anything in the record actually refers to. */
  documentsReferredTo: number;
}

export type SoftSpot =
  | 'nothing else touches it'
  | 'the detail does not move'
  | 'documents nobody uses';

/**
 * Where the record is easiest to be wrong about, and why.
 *
 * Deliberately phrased so that every line is true of the RECORD and false as a
 * statement about a person. "Nothing else in the ground touches this" is a fact
 * about coverage. "This person is not corroborated" is an insinuation.
 */
export function softSpots(a: AccountShape): { spot: SoftSpot; line: string }[] {
  const out: { spot: SoftSpot; line: string }[] = [];

  // A whole account nobody else's account reaches. Usually means the others
  // simply worked elsewhere, which is exactly why this lowers confidence rather
  // than raising suspicion.
  /**
   * TWO CORROBORABLE STATEMENTS BEFORE THIS CAN FIRE, and the reason is a probe
   * rather than a theory: a lead stating targets across five sessions came back
   * with corroborated: 0 and got this spot, which lowered confidence in the picture
   * because they had done their job. Where the number is absent, the old behaviour
   * stands - callers written before this existed are not silently changed.
   */
  const couldHaveBeenChecked = a.corroborable ?? Infinity;
  if (a.sessions >= 2 && a.corroborated === 0 && couldHaveBeenChecked >= 2) {
    out.push({
      spot: 'nothing else touches it',
      line: 'Nothing else in this ground touches any part of this account. That does not make it wrong, it makes it unchecked: it rests entirely on one person having described it accurately.',
    });
  }

  // Detail that never moves. Innocent on a stable project, and the single
  // cheapest thing to produce if somebody is writing what they think is wanted.
  if (a.specifics >= 3 && a.repeatedSpecifics / a.specifics > 0.6) {
    out.push({
      spot: 'the detail does not move',
      line: 'The specifics here are mostly the same specifics session after session. On steady work that is what steady work looks like; it also means the record has not been updated in a way anybody could notice.',
    });
  }

  // Attached and never used. The signal that is easiest to satisfy on purpose,
  // because attaching is one click and reading is not.
  if (a.documents >= 1 && a.documentsReferredTo === 0) {
    out.push({
      spot: 'documents nobody uses',
      line: 'Documents are attached here but nothing in the record refers to them. The documents are not doing any work in this picture, so treat this as an account without documents rather than one with them.',
    });
  }

  return out;
}

/**
 * G34's actual guarantee, stated as a function so it can be asserted rather than
 * promised in a comment: a soft spot never travels alone. Whatever lowers
 * confidence also says what would raise it.
 *
 * Without this, the honest half of the feature ("we are less sure here") arrives
 * as the accusing half ("something is off about this person"), which is the exact
 * failure the module exists to avoid.
 */
export function whatWouldRaiseIt(spot: SoftSpot): string {
  switch (spot) {
    case 'nothing else touches it':
      return 'Ask one other person about any single part of it. One overlap is the difference between an unchecked account and a checked one.';
    case 'the detail does not move':
      return 'Ask what changed since last time, and accept "nothing" as an answer. A recorded "nothing changed" is worth more than a repeated description.';
    case 'documents nobody uses':
      return 'Ask what in the attached documents anybody should be reading, or leave them out.';
  }
}

/**
 * G35. The one rule the whole module is scaffolding for.
 *
 * A reader takes a board at the confidence the board projects, so the moment a
 * read is not supported the product has to say that MORE loudly than it says the
 * read - not in a footnote, not in grey, and not after it.
 */
export function readIsSafeToShow(
  read: { line: string },
  confidence: { band: string },
  spots: { spot: SoftSpot }[],
): { show: boolean; instead: string | null } {
  const unsupported = confidence.band === 'thin' || confidence.band === 'nothing yet' || spots.length >= 2;
  if (!unsupported) return { show: true, instead: null };

  return {
    show: false,
    instead:
      'There is not enough here to draw a reading from. What is missing is described above; a reading built on this would be a guess wearing a report\'s clothes.',
  };
}

/**
 * And the sentence a board carries when it is showing less than somebody hoped.
 *
 * Written to be readable as a good outcome, because it is one. A product that
 * refuses to guess is doing the job; a product that guesses quietly is the
 * liability G35 names.
 */
export const NOT_ENOUGH_HERE =
  'Some parts of this board are blank because the record does not support them yet. Blank is a finding: it says where to look next, and it is the honest state until somebody says more.';
